version: '3'
services:
  nginx:
    image: dpwrussell/omero-nginx
    links:
      - web
    ports:
      - "8080:80"
  web:
    image: dpwrussell/omero-web
    # environment:
    #   CONFIG_omero_web_public_enabled: "true"
    #   CONFIG_omero_web_public_user: public-user
    #   CONFIG_omero_web_public_password: omero
    #   CONFIG_omero_web_public_url__filter: "^/(?!webadmin|webclient/(action|logout|annotate_(file|tags|comment|rating|map)|script_ui|ome_tiff|figure_script)|webgateway/(archived_files|download_as))"
    links:
      - omero:master
    ports:
     - "4080:4080"
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: postgres
  omero:
    image: dpwrussell/omero.cloudarchive
    environment:
      CONFIG_omero_db_user: postgres
      CONFIG_omero_db_pass: postgres
      CONFIG_omero_db_name: postgres
      ROOTPASS: omero
      # S3_BUCKET: "s3://dpwr/d3"
      # CONFIG_omero_web_public_enabled: "true"
    links:
      - db
    ports:
      - "4063:4063"
      - "4064:4064"
