version: '3'
services:
  # web:
  #   image: dpwrussell/omero-grid-web
  #   environment:
  #     PUBLIC_GROUP: public-group
  #   links:
  #     - omero:master
  #   ports:
  #    - "8080:8080"
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: postgres
  omero:
    image: dpwrussell/omero.cloudarchive
    environment:
      CONFIG_omero_db_user: postgres
      CONFIG_omero_db_pass: postgres
      CONFIG_omero_db_name: postgres
      ROOTPASS: omero
      # S3_BUCKET: "s3://dpwr/d3"
      # CONFIG_omero_web_public_enabled: "true"
    links:
      - db
    ports:
      - "4063:4063"
      - "4064:4064"
